spring.application.name=palaisdivin-backend
spring.threads.virtual.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized
springdoc.writer-with-order-by-keys=true
springdoc.writer-with-default-pretty-printer=true
